<html>
<head>
<!-- header is included this is ran at the start of every file -->
<?php include('includes/header.php'); ?>
<!-- php include was adapted from https://stackoverflow.com/questions/18712338/make-header-and-footer-files-to-be-included-in-multiple-html-pages -->
</head>
<body> 
<!-- given a class to edit with css -->
<main class = "content-box">

<!-- info displayed on homepage -->
<h2>Hello and welcome to the Website!</h2> 

<h3>This is the homepage where im going to give you a brief description of the overall structure of the website.
Firstly, An example dataset can be examined, this was generated by quering "Aves" and "glucose-6-phosphatase" with a max sequences of 10. 
This section allows the user to get familiar with the outputs generated by the analysis. These include: </h3>
<h3><li>Clustalo Alignment</li></h3>
<h3><li>Sequence conservation plot using EMBOSS plotcon</li></h3>
<h3><li>PROSITE motif using patmatmotifs</li></h3>
<h3><li>Statistics of protein properties using EMBOSS pepstats</li></h3>
<h3><p> The custom search function allows the user to enter there own queries by stating a taxonomic group, protein family and number of results
these are then displayed back in table form for the user to view. Additonally, the user can click "Use Example" to perform a live query of the example data.
The max sequences for this was set to 3 however, this is just for more beneficial formating and can be set to any value up until 30 (arbitrary cutoff)</p></h3>

<h3><p> Finally, all "Completed" jobs where seqeunces are successfully queried from NCBI are stored in the previous analysises page for user to examine. 
This allows for users to refer back to their own analyses and also see the queries of others.</p></h3>
<h3><p> A github repository of the code can be found <a href ="https://github.com/B290062/Website">here</a> before clicking it worth noting that my full name is attached to the repository
. I tried to remove this by renaming my github username to my exam number but I already did multiple commits, apologies.</h3>
</main>
</body>